#!/bin/sh

## LUCKY: that jsh puts itself before this script in the PATH, otherwise it'd call itself recursively!

export CGILIB_NO_CONTENT=true
. cgilib
export JPATH=/home/joey/j
. /home/joey/j/startj-simple

SCRIPT="`getcgi script`"

if [ ! -f "$JPATH/tools/$SCRIPT" ]
then
	simpleresponseheader
	echo "The file you requested was not found at the expected location: $JPATH/tools/$SCRIPT"
	exit 0
fi

TMPDIR=`jgettmpdir compiling:$SCRIPT`
TMPSCRIPT="$TMPDIR/$SCRIPT.sh"

echo "`date` [$$] compilejshscript: Compiling $SCRIPT" >&2

export DEPWIZ_NON_INTERACTIVE=true

## If we want to make sure they get everything they need for scripts without defined dependency meta:
export DEPWIZ_VIGILANT=true

## But if we want it faster: ## TODO: hmmm doesn't appear to be any faster.
# export DEPWIZ_VIGILANT=
# export DEPWIZ_LAZY=true

compilejshscript "$SCRIPT" > $TMPSCRIPT 2> /tmp/compilejshscript.log

## Pretty print output to apache log:
# trimempty | sed "s+^+`date` [$$] compilejshscript:   +" >&2

## Send output to apache log (realtime):
# cat >&2

## Discard output:
# cat > /dev/null

echo "`date` [$$] compilejshscript: Done" >&2

serve "$TMPSCRIPT"

jdeltmpdir $TMPDIR
