#!/bin/sh

. cgilib
# export JPATH=/home/joey/j
# . /home/joey/j/startj-simple

SESSID=`getcgi "sessid"`
INIT=`getcgi "init"`

if test "$INIT" = true; then

	echo "" > /tmp/revssh-client-input-$SESSID.txt
	echo "" > /tmp/revssh-client-output-$SESSID.txt
	chmod ugo+w /tmp/revssh-client-input-$SESSID.txt
	chmod ugo+r /tmp/revssh-client-output-$SESSID.txt
	tail -f /tmp/revssh-client-input-$SESSID.txt

else

	OUTPUT=`getcgi "output"`

	echo "$OUTPUT" >> /tmp/revssh-client-output-$SESSID.txt

fi
