#!/bin/sh

echo "Content-type: text/html"
echo

. cgilib
export JPATH=/home/joey/j
. /home/joey/j/startj-simple

# set | tohtml

WHOTO=`echo "$QUERY_STRING" | sed "s/.*\(&\|'\)\([^_]*\)_submit=Send+email.*/\2/" | fromcgi`

# This line unfinished:
EMAILTO=`getcgi "$WHOTO"_to | sed "s/^\([A:Z,a:z,.]*@[A:Z,a:z,.]*\)$/GOT:\1/"`
EMAILSUBJECT=`getcgi "$WHOTO"_subject`
EMAILBODY=`getcgi "$WHOTO"_body`

echo "\"$EMAILTO\""
echo "<br>"
echo "\"$EMAILSUBJECT\""
echo "<br>"
echo "\"$EMAILBODY\""

exit 0

(
	echo "From: "`getcgi fromname`" <"`getcgi from`">"
	echo "Address: "`getcgi address`
	echo
	echo "$EMAILBODY"
) | mail -s "$EMAILSUBJECT" "$EMAILTO"
