#!/bin/sh

## Now slower, but works on XML documents (previously produced nothing for them).
## This is needed for show_minitools.xsl

. cgilib
export JPATH=/home/joey/j
. /home/joey/j/startj-simple

URL="`getcgi "url"`"

## These are security measures.
## TODO: Convert them to what they should be (eg. "s would need to be escaped to go inside the memo's \"s).
URL=`echo "$URL" | tr -d '"'"'"`
# URL=`echo "$URL" | sed 's+:1:$++'` ## Fix for XSLT bug, probably not needed
## TODO: I am still worried about this memo; because it will eval!
##       and even after above fixed, what about eg. CTRL-chars?
## And what escaping gets lost when we use echo above?  echovar?!

# wget -nv -O - "$URL" | tidy -asxml

# /home/joey/j/jsh memo "
# wget -nv -O - \"$URL\" |
# sed 's+&nbsp;++g' |
# tidy -asxml ; true
# "

# wget -nv -O - "$URL" | sed 's+&nbsp;++g' | tidy -asxml
# /home/joey/j/jsh memo wget -nv -O - "$URL" | sed 's+&nbsp;++g' | tidy -asxml ; true
# /home/joey/j/jsh memo "wget -nv -O - \"$URL\" | sed 's+&nbsp;++g' | tidy -asxml ; true"

## CONSIDER: Try jtidy to avoid getting empty results.

# /home/joey/j/jsh memo -t "1 hour" wget -nv -O - "$URL" | sed 's+&nbsp;++g' > /tmp/tmpfile
# cat /tmp/tmpfile | tidy -asxml > /tmp/tmpfile.tidied 2> /tmp/tidy.err
# if grep . /tmp/tmpfile.tidied >/dev/null
# then cat /tmp/tmpfile.tidied
# else
	# echo "<FAILURE>W3C Tidy could not tidy this document because it has too many errors.  Sorry I wish it would do better than nothing!</FAILURE>"
	# # cat /tmp/tmpfile
# fi


function try_with_options () {
	OPTIONS="$1"
	cat "$INFILE" |
	sed 's+&nbsp;++g' |
	verbosely tidy $OPTIONS >"$OUTFILE" 2>"$OUTFILE.err"
	# cat "$OUTFILE" | grep .
	if [ -s "$OUTFILE" ]
	then
		cat "$OUTFILE"
		return 0
	else
		return 1
	fi
}

INFILE=`jgettmp tidy_in`
OUTFILE=`jgettmp tidy_out`

# MEMOTIME="1 hour"
MEMOTIME="2 minutes"
IKNOWIDONTHAVEATTY=1 memo -t "$MEMOTIME" wget -nv -O - "$URL" > "$INFILE"

for OPTIONS in -asxml -xml
do try_with_options "$OPTIONS" && break
done

if [ ! "$?" = 0 ]
then echo "<FAILURE>W3C Tidy could not tidy this document because it has too many errors.  Sorry I wish it would do better than nothing!</FAILURE>"
fi

# echo "Got $URL" > /tmp/tidy.got

jdeltmp "$INFILE" "$OUTFILE" "$OUTFILE".err

