#!/bin/sh

[ "$1" = "" ] && echo "grammar name?" && exit 0

name="$1"

info() {
  echo
  echo "$@"
}

# If CVS leaves files read-only, these can end up being copied into build/ and
# bin/ and then I can't recompile my grammars and I get annoyed.
chmod u+rw src build bin -R

cd src/tools/parser || exit 3

info "Parsing grammar $1.grm"

mv "$1Grm.java" "$1Grm.java.b4create"
# echo "package tools.parser;"
jparse grm "$1.grm" java $2 $3 $4 $5 $6 > "$1Grm.java"
success="$?"
sedreplace "grmGrm" "$1Grm" "$1Grm.java"
if [ ! "$success" = 0 ]
then
	echo "jparse failed - not trying to compile."
	exit 4
fi
#mv "$1Grm.java" tmp.txt
#mv tmp.txt "$1Grm.java"
# jfcsh "$1Grm.java.b4create" "$1Grm.java"
# diff "$1Grm.java.b4create" "$1Grm.java" | diffhighlight -nm
diffsummary "$1Grm.java.b4create" "$1Grm.java"

cd ../../..

info "Building new Java ruleset"

# ./build.sh
# cd src
# javac tools/parser/"$1Grm.java"
# success="$?"
# if [ "$success" ]
# then
	# mv -f tools/parser/"$1Grm.class" ../bin/tools/parser/"$1Grm.class"
if cp src/tools/parser/"$1Grm.java" bin/tools/parser/"$1Grm.java" &&
	cd bin &&
	javac tools/parser/"$1Grm.java"
then
	echo "New grammar \"$1\" compiled and ready to try!"
else
	echo "Failed to compile the new ruleset!"
	exit 6
fi

