#!/bin/bash

# echo -n "Redefine the parser's grammar grammar (y/n)? "
# read X
# [ "$X" = "y" ] || exit 9

info() {
  echo
  echo "$@"
}

failandquit() {

  newFile="$1"
  [ -z "$newFile" ] && newFile="$gdir"/grmGrm.java.new

  # Display the problem
  info "Bad grammar!  Here are the first generation differences:"
  #jfcsh "$gdir"/grmGrm.java "$gdir"/grmGrm.java.2
  diff "$gdir"/grmGrm.java.previous "$newFile" | diffhighlight -nm

  # Reset to original
  info "Bad grammar!  Restoring original..."
  cp -a "$gdir"/grmGrm.java "$gdir"/grmGrm.java.failed
  cp -a "$gdir"/grmGrm.java.previous "$gdir"/grmGrm.java
  ./build.sh
  restored="$?"

  info "Check files $gdir/grmGrm.java.new and $gdir/grmGrm.java.failed"

  if [ "$restored" = 0 ]
  then
    info "Original grammar restored.  Please fix $gdir/grm.grm"
  else
    info "FAILED to restore original grammar!  Sorry about that."
    exit 99
  fi
  exit 4
}

# If CVS leaves files read-only, these can end up being copied into build/ and
# bin/ and then I can't recompile my grammars and I get annoyed.
chmod u+rw src build bin -R

gdir="src/tools/parser"

info "Compiling everything, making backup."
./build.sh || exit 91
cp -a "$gdir"/grmGrm.java "$gdir"/grmGrm.java.previous

rm -f "$gdir"/grmGrm.java.2

info "Converting grammar into javadecl ruleset"
jparse grm "$gdir"/grm.grm javadecl "$@" > "$gdir"/grmGrm.java || failandquit
[ "$?" = 0 ] || failandquit
if [ "$1" = "debug" ]; then
  edit "$gdir"/grmGrm.java
fi
cp "$gdir"/grmGrm.java "$gdir"/grmGrm.java.new

info "Compiling new grammar"
./build.sh || failandquit

info "Test: Converting using new grammar"
jparse grm "$gdir"/grm.grm javadecl $@ > "$gdir"/grmGrm.java || failandquit
if [ "$1" = "debug" ]; then
  edit "$gdir"/grmGrm.java
fi

info "Are they different?"
set +e
if ! cmp "$gdir"/grmGrm.java.previous "$gdir"/grmGrm.java
then
  echo "Changes are:"
  # diff "$gdir"/grmGrm.java.previous "$gdir"/grmGrm.java | diffhighlight -nm
  JDSCONTEXT="-C2" jdiffsimple "$gdir"/grmGrm.java.previous "$gdir"/grmGrm.java
fi
set -e

info "Test: Convert once again"
./build.sh || failandquit

info "Creating final ruleset to compare"
jparse grm "$gdir"/grm.grm javadecl $@ > "$gdir"/grmGrm.java.2 || failandquit "$gdir"/grmGrm.java.2
if [ "$1" = "debug" ]; then
  edit "$gdir"/grmGrm.java
fi

info "Comparing first and second generations"
if cmp "$gdir"/grmGrm.java "$gdir"/grmGrm.java.2 > /dev/null 2>&1 ; then
  echo "New grammar installed OK"
else
  failandquit "$gdir"/grmGrm.java.2
fi

# echo "stringhash=$# stringunderscore=$_"

exit 0
