#!/bin/sh

set -e

# I use the jparse wrapper to call the parser.  You may not have it, so...
if !which jparse >/dev/null 2>&1
then
	buildPath="$PWD/build"
	jparse() {
		java -cp "$buildPath" tools.parser.Parser "$@"
	}
fi

./newgrammar

# ./creategrammar dlang
# jparse dlang spiral.d

./test_dlang

echo
echo
echo "Balling up a backup."
tar cfz last_working_build.tgz src/ bin/ &
# Beware: Since this tarball contains CVS folders, it can disrupt your local CVS status if it's old!

mkdir -p backups
cp -f ./last_working_build.tgz backups/last_working_build.tgz
rotate -keep -nozip -max 5 backups/last_working_build.tgz

echo "Build all the grammars."
./creategrammar c
./creategrammar marff
./creategrammar xml
# ./creategrammar dlang
./creategrammar calc && jparse calc testdata/calculator_expression_1.txt build

